title: Royal Engineers
description: > # this means to ignore newlines until "baseurl:"
  E păcat să pui șurub unde stă cu scotch sau colier
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://royalengineers.ro" # the base hostname & protocol for your site

# facebook:
#   app_id: 

logo: "../css/2023_style/img/logos_echipa/coroana finala - nobg.png"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2023_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100093273202312
  - title: instagram
    url: https://www.instagram.com/royal.engineers_/
  - title: tiktok
    url: https://www.tiktok.com/@royal.engineers
  - title: youtube
    url: https://www.youtube.com/@royalengineerss2636
# Build settings
markdown: kramdown
permalink: pretty
